###############################################################################
# Created by write_sdc
# Sat Sep 17 00:32:15 2022
###############################################################################
current_design digital_unison
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk_master -period 400.0000 [get_ports {clk_master}]
set_clock_transition 0.1500 [get_clocks {clk_master}]
set_clock_uncertainty 0.2500 clk_master
set_propagated_clock [get_clocks {clk_master}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_I[0]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_I[1]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_I[2]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_I[3]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_I[4]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_I[5]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_I[6]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_I[7]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_Q[0]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_Q[1]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_Q[2]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_Q[3]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_Q[4]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_Q[5]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_Q[6]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {comp_high_Q[7]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_I[0]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_I[1]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_I[2]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_I[3]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_I[4]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_I[5]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_I[6]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_I[7]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_Q[0]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_Q[1]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_Q[2]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_Q[3]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_Q[4]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_Q[5]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_Q[6]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {phi1b_dig_Q[7]}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {rstb}]
set_input_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {ud_en}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_I[0]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_I[1]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_I[2]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_I[3]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_I[4]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_I[5]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_I[6]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_I[7]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_Q[0]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_Q[1]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_Q[2]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_Q[3]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_Q[4]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_Q[5]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_Q[6]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cclk_Q[7]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_I[0]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_I[1]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_I[2]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_I[3]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_I[4]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_I[5]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_I[6]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_I[7]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_Q[0]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_Q[1]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_Q[2]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_Q[3]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_Q[4]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_Q[5]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_Q[6]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {clkdiv2_Q[7]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cos_out[0]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cos_out[1]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cos_out[2]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cos_out[3]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cos_out[4]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cos_out[5]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cos_out[6]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {cos_out[7]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_I[0]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_I[1]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_I[2]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_I[3]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_I[4]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_I[5]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_I[6]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_I[7]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_Q[0]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_Q[1]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_Q[2]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_Q[3]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_Q[4]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_Q[5]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_Q[6]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {fb1_Q[7]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {read_out_I[0]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {read_out_I[1]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {read_out_Q[0]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {read_out_Q[1]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {sin_out[0]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {sin_out[1]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {sin_out[2]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {sin_out[3]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {sin_out[4]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {sin_out[5]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {sin_out[6]}]
set_output_delay 80.0000 -clock [get_clocks {clk_master}] -add_delay [get_ports {sin_out[7]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {cclk_I[7]}]
set_load -pin_load 0.0334 [get_ports {cclk_I[6]}]
set_load -pin_load 0.0334 [get_ports {cclk_I[5]}]
set_load -pin_load 0.0334 [get_ports {cclk_I[4]}]
set_load -pin_load 0.0334 [get_ports {cclk_I[3]}]
set_load -pin_load 0.0334 [get_ports {cclk_I[2]}]
set_load -pin_load 0.0334 [get_ports {cclk_I[1]}]
set_load -pin_load 0.0334 [get_ports {cclk_I[0]}]
set_load -pin_load 0.0334 [get_ports {cclk_Q[7]}]
set_load -pin_load 0.0334 [get_ports {cclk_Q[6]}]
set_load -pin_load 0.0334 [get_ports {cclk_Q[5]}]
set_load -pin_load 0.0334 [get_ports {cclk_Q[4]}]
set_load -pin_load 0.0334 [get_ports {cclk_Q[3]}]
set_load -pin_load 0.0334 [get_ports {cclk_Q[2]}]
set_load -pin_load 0.0334 [get_ports {cclk_Q[1]}]
set_load -pin_load 0.0334 [get_ports {cclk_Q[0]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_I[7]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_I[6]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_I[5]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_I[4]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_I[3]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_I[2]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_I[1]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_I[0]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_Q[7]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_Q[6]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_Q[5]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_Q[4]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_Q[3]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_Q[2]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_Q[1]}]
set_load -pin_load 0.0334 [get_ports {clkdiv2_Q[0]}]
set_load -pin_load 0.0334 [get_ports {cos_out[7]}]
set_load -pin_load 0.0334 [get_ports {cos_out[6]}]
set_load -pin_load 0.0334 [get_ports {cos_out[5]}]
set_load -pin_load 0.0334 [get_ports {cos_out[4]}]
set_load -pin_load 0.0334 [get_ports {cos_out[3]}]
set_load -pin_load 0.0334 [get_ports {cos_out[2]}]
set_load -pin_load 0.0334 [get_ports {cos_out[1]}]
set_load -pin_load 0.0334 [get_ports {cos_out[0]}]
set_load -pin_load 0.0334 [get_ports {fb1_I[7]}]
set_load -pin_load 0.0334 [get_ports {fb1_I[6]}]
set_load -pin_load 0.0334 [get_ports {fb1_I[5]}]
set_load -pin_load 0.0334 [get_ports {fb1_I[4]}]
set_load -pin_load 0.0334 [get_ports {fb1_I[3]}]
set_load -pin_load 0.0334 [get_ports {fb1_I[2]}]
set_load -pin_load 0.0334 [get_ports {fb1_I[1]}]
set_load -pin_load 0.0334 [get_ports {fb1_I[0]}]
set_load -pin_load 0.0334 [get_ports {fb1_Q[7]}]
set_load -pin_load 0.0334 [get_ports {fb1_Q[6]}]
set_load -pin_load 0.0334 [get_ports {fb1_Q[5]}]
set_load -pin_load 0.0334 [get_ports {fb1_Q[4]}]
set_load -pin_load 0.0334 [get_ports {fb1_Q[3]}]
set_load -pin_load 0.0334 [get_ports {fb1_Q[2]}]
set_load -pin_load 0.0334 [get_ports {fb1_Q[1]}]
set_load -pin_load 0.0334 [get_ports {fb1_Q[0]}]
set_load -pin_load 0.0334 [get_ports {read_out_I[1]}]
set_load -pin_load 0.0334 [get_ports {read_out_I[0]}]
set_load -pin_load 0.0334 [get_ports {read_out_Q[1]}]
set_load -pin_load 0.0334 [get_ports {read_out_Q[0]}]
set_load -pin_load 0.0334 [get_ports {sin_out[7]}]
set_load -pin_load 0.0334 [get_ports {sin_out[6]}]
set_load -pin_load 0.0334 [get_ports {sin_out[5]}]
set_load -pin_load 0.0334 [get_ports {sin_out[4]}]
set_load -pin_load 0.0334 [get_ports {sin_out[3]}]
set_load -pin_load 0.0334 [get_ports {sin_out[2]}]
set_load -pin_load 0.0334 [get_ports {sin_out[1]}]
set_load -pin_load 0.0334 [get_ports {sin_out[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk_master}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rstb}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ud_en}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_I[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_I[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_I[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_I[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_I[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_I[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_I[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_I[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_Q[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_Q[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_Q[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_Q[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_Q[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_Q[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_Q[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {comp_high_Q[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_I[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_I[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_I[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_I[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_I[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_I[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_I[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_I[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_Q[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_Q[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_Q[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_Q[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_Q[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_Q[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_Q[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {phi1b_dig_Q[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
